title: "Spacecraft Communications Weapons School"
author: "Dimitriy Georgiev"
description: "Spacecraft Communications" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "d.v.georgiev@st.hanze.nl"
github_username: "Silverlined"
#linkedin_username: "dimitriy-georgiev-in"
#twitter_username: "twitteruser"
#facebook_username: username
#flickr_username: username
#instagram_username: "dimitriy_georgiev"
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"
future: true

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
      
titles_from_headings:
  strip_title: true
  collections: true

defaults:
  -
    scope:
      path: "_posts/*.md" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "_posts/sc2021/*"
    values:
      layout: "post"
      tags: SC2021
  -
    scope:
      path: "_posts/digital_communications_2024/*"
    values:
      layout: "post"
      tags: DC2024