version: '3.3'
services:
  jekyll:
    volumes:
        - './:/srv/jekyll'
    network_mode: host
    # ports:
    #     - '4001:4001'
    #     - '35729:35729'
    image: jekyll/jekyll
    command: sh -c "jekyll clean && jekyll serve --host 127.0.0.1 --port 4001 --incremental --livereload --force_polling"
    #command: jekyll serve --incremental --livereload --force_polling
